name: Docker Image CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v4

      # Login to "owntube" organization on Docker Hub
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build minio-client image
      - name: Build the `owntube/minio-client` Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 . --tag owntube/minio-client:2024.3.30-debian-12-r2

      # Test minio-client image
      - name: Test the `owntube/minio-client` Docker image
        run: docker run -i --rm --name minio-client-mc-version owntube/minio-client:2024.3.30-debian-12-r2 mc version

      # Push minio-client image
      - name: Push the `owntube/peertube-runner:v603` Docker image
        run: docker push owntube/minio-client:2024.3.30-debian-12-r2

      # Logout, as logout=true from `docker/login-action@v3` does not seem to work
      - run: docker logout index.docker.io
